/*
 * Copyright The Asahi Linux Contributors
 * Contributed by Myria Sarvay <myrialsarvay@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Apple M4 Events
 * Hardware events extracted from /usr/share/kpep on macos
 */
static const arm_entry_t arm_apple_m4_pe[]={
	{.name = "ARM_L1D_CACHE_REFILL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3,
	 .desc = "Level 1 data cache refill",
	},
	{.name = "ARM_L1D_CACHE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x4,
	 .desc = "Level 1 data cache access",
	},
	{.name = "INST_ALL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8,
	 .desc = "All retired instructions",
	},
	{.name = "ARM_BR_MIS_PRED",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x10,
	 .desc = "Mispredicted or not predicted branch Speculatively executed",
	},
	{.name = "CORE_ACTIVE_CYCLE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x11,
	 .desc = "Cycles while the core was active",
	},
	{.name = "ARM_BR_PRED",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x12,
	 .desc = "Predictable branch Speculatively executed",
	},
	{.name = "INST_BRANCH",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x21,
	 .desc = "Retired branch instructions including calls and returns",
	},
	{.name = "BRANCH_MISPRED_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x22,
	 .desc = "Instruction architecturally executed, mispredicted branch",
	},
	{.name = "ARM_STALL_FRONTEND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x23,
	 .desc = "No operation issued due to the frontend",
	},
	{.name = "ARM_STALL_BACKEND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x24,
	 .desc = "No operation issued due to the backend",
	},
	{.name = "ARM_L1D_CACHE_LMISS_RD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x39,
	 .desc = "Level 1 data cache long-latency read miss",
	},
	{.name = "RETIRE_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3a,
	 .desc = "All retired uops",
	},
	{.name = "MAP_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3b,
	 .desc = "Mapped uops",
	},
	{.name = "ARM_STALL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3c,
	 .desc = "No operation sent for execution",
	},
	{.name = "ARM_STALL_SLOT_BACKEND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3d,
	 .desc = "No operation sent for execution on a Slot due to the backend",
	},
	{.name = "ARM_STALL_SLOT_FRONTEND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3e,
	 .desc = "No operation sent for execution on a Slot due to the frontend",
	},
	{.name = "ARM_STALL_SLOT",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x3f,
	 .desc = "No operation sent for execution on a slot",
	},
	{.name = "ARM_L1D_CACHE_RD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x40,
	 .desc = "Attributable Level 1 data cache access, read",
	},
	{.name = "MAP_DISPATCH_BUBBLE_IC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x182,
	 .desc = "Cycles while the Map Unit had no uops to process due to L1 Instruction Cache and was not stalled",
	},
	{.name = "MAP_DISPATCH_BUBBLE_ITLB",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x183,
	 .desc = "Cycles while the Map Unit had no uops to process due to L1 Instruction TLB and was not stalled",
	},
	{.name = "DECODE_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x186,
	 .desc = "Decoded uops",
	},
	{.name = "L1I_TLB_MISS_DEMAND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x1d4,
	 .desc = "Demand instruction fetches that missed in the L1 Instruction TLB",
	},
	{.name = "MAP_DISPATCH_BUBBLE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x1d6,
	 .desc = "Cycles while the Map Unit had no uops to process and was not stalled",
	},
	{.name = "FETCH_RESTART",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x1de,
	 .desc = "Fetch Unit internal restarts for any reason. Does not include branch mispredicts",
	},
	{.name = "MAP_DISPATCH_BUBBLE_SLOT",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x1e1,
	 .desc = "Slots where the Map Unit had no uops to process and was not stalled",
	},
	{.name = "INTERRUPT_PENDING",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x26c,
	 .desc = "Cycles while an interrupt was pending because it was masked",
	},
	{.name = "MAP_STALL_DISPATCH",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x270,
	 .desc = "Cycles while the Map Unit was stalled because of Dispatch back pressure",
	},
	{.name = "MAP_REWIND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x275,
	 .desc = "Cycles while the Map Unit was blocked while rewinding due to flush and restart",
	},
	{.name = "MAP_STALL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x276,
	 .desc = "Cycles while the Map Unit was stalled for any reason",
	},
	{.name = "MAP_INT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x27c,
	 .desc = "Mapped Integer Unit uops",
	},
	{.name = "MAP_LDST_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x27d,
	 .desc = "Mapped Load and Store Unit uops, including GPR to vector register converts.  Includes all instructions sent to the SME engine because they are processed through the Store Unit.",
	},
	{.name = "MAP_SIMD_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x27e,
	 .desc = "Mapped Advanced SIMD and FP Unit uops",
	},
	{.name = "SCHEDULE_UOP_ANY",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x283,
	 .desc = "Cycles while the uop scheduler issued at least 1 uop to any execution unit",
	},
	{.name = "MAP_INT_SME_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x285,
	 .desc = "Mapped core Integer Unit uops for SME engine instructions",
	},
	{.name = "SME_ENGINE_SM_ENABLE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x286,
	 .desc = "Transitions into SME engine Streaming Mode (PSTATE.SM: 0 to 1)",
	},
	{.name = "SME_ENGINE_SM_ZA_ENABLE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x287,
	 .desc = "Simultaneous transitions into SME engine Streaming Mode and ZA Mode (PSTATE.SM: 0 to 1 and PSTATE.ZA: 0 to 1)",
	},
	{.name = "SME_ENGINE_ZA_ENABLED_SM_DISABLED",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x288,
	 .desc = "Cycles while SME engine ZA Mode is enabled but Streaming Mode is not (PSTATE.ZA=1 and PSTATE.SM=0)",
	},
	{.name = "LDST_UNIT_WAITING_SME_ENGINE_INST_QUEUE_FULL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x28c,
	 .desc = "Cycles while the instruction queue to the SME engine is full, and no uop was issued by the scheduler with no critical miss, prioritized",
	},
	{.name = "SCHEDULE_WAITING_SME_ENGINE_REG_DATA",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x28e,
	 .desc = "Cycles while the core is waiting for register, predicate, or flag data from the SME engine, and no uop was issued by the scheduler with no critical miss, prioritized",
	},
	{.name = "LDST_UNIT_WAITING_SME_ENGINE_MEM_DATA",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x28f,
	 .desc = "Cycles while the core is waiting for the SME engine to produce memory data, and no uop was issued by the scheduler, prioritized",
	},
	{.name = "LDST_UNIT_OLD_L1D_CACHE_MISS",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x290,
	 .desc = "Cycles while an old load or store uop is waiting for data after an L1 Data Cache miss",
	},
	{.name = "LDST_UNIT_WAITING_OLD_L1D_CACHE_MISS",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x291,
	 .desc = "Cycles while an old load or store uop is waiting for data after an L1 Data Cache miss, and no uop was issued by the scheduler, prioritized",
	},
	{.name = "LD_UNIT_WAITING_YOUNG_L1D_CACHE_MISS",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x294,
	 .desc = "Cycles while a younger load uop is waiting for data after an L1 Data Cache miss, and no uop was issued by the scheduler with no critical miss, prioritized",
	},
	{.name = "MAP_RECOVERY",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x2ad,
	 .desc = "Cycles while the Map Unit was stalled while recovering from a flush and restart",
	},
	{.name = "MAP_STALL_NONRECOVERY",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x2ae,
	 .desc = "Cycles while the Map Unit was stalled for any reason other than recovery",
	},
	{.name = "SCHEDULE_EMPTY",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x351,
	 .desc = "Cycles while the uop scheduler is empty",
	},
	{.name = "L1I_TLB_FILL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x404,
	 .desc = "Translations filled into the L1 Instruction TLB",
	},
	{.name = "L1D_TLB_FILL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x405,
	 .desc = "Translations filled into the L1 Data TLB",
	},
	{.name = "MMU_TABLE_WALK_INSTRUCTION",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x407,
	 .desc = "Table walk memory requests on behalf of instruction fetches",
	},
	{.name = "MMU_TABLE_WALK_DATA",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x408,
	 .desc = "Table walk memory requests on behalf of data accesses",
	},
	{.name = "L2_TLB_MISS_INSTRUCTION",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x40a,
	 .desc = "Instruction fetches that missed in the L2 TLB",
	},
	{.name = "L2_TLB_MISS_DATA",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x40b,
	 .desc = "Loads and stores that missed in the L2 TLB",
	},
	{.name = "LDST_SME_XPG_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x508,
	 .desc = "SME engine load and store accesses that crossed a 16KiB page boundary.  An access is considered cross-page if any bytes are accessed in the high portion (second page), regardless if any bytes are accessed in the low portion (first page), after predication is applied. An SME operation that only touches the low portion (first page) after predication is applied is not considered cross-page.",
	},
	{.name = "INST_SME_ENGINE_PACKING_FUSED",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x529,
	 .desc = "Retired non-load/store SME engine instructions that were packed with another to reduce instruction bandwidth to the SME engine",
	},
	{.name = "LD_BLOCKED_BY_SME_LDST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x52c,
	 .desc = "Core load uops blocked by SME accesses to same 4KiB page",
	},
	{.name = "ST_BARRIER_BLOCKED_BY_SME_LDST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x52e,
	 .desc = "Core store uops blocked by SME accesses to same 4KiB page, and any barriers or store-release uops blocked by SME accesses",
	},
	{.name = "LD_SME_NT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x573,
	 .desc = "SME engine load uops that executed with non-temporal hint",
	},
	{.name = "ST_SME_NT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x574,
	 .desc = "SME engine store uops that executed with non-temporal hint",
	},
	{.name = "LD_SME_NORMAL_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x575,
	 .desc = "SME engine load uops with Normal memory type",
	},
	{.name = "ST_SME_NORMAL_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x576,
	 .desc = "SME engine store uops with Normal memory type",
	},
	{.name = "LDST_SME_PRED_INACTIVE",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x577,
	 .desc = "SME engine load and store uops where all lanes are inactive due to the governing predicate.  For a page-crossing load or store, the event may incorrectly count when all of the elements of the low page are predicated off, even if some of the elements on the high page are active. In Apple silicon cores, where predication is recommend primarily for data structure edge control (discarding elements 'past the end of the data structure'), this scenario should not be common.",
	},
	{.name = "L1D_TLB_ACCESS",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a0,
	 .desc = "Load and store accesses to the L1 Data TLB",
	},
	{.name = "L1D_TLB_MISS",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a1,
	 .desc = "Load and store accesses that missed the L1 Data TLB",
	},
	{.name = "L1D_CACHE_MISS_ST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a2,
	 .desc = "Stores that missed the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_LD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a3,
	 .desc = "Loads that missed the L1 Data Cache",
	},
	{.name = "LD_UNIT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a6,
	 .desc = "Uops that flowed through the Load Unit",
	},
	{.name = "ST_UNIT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a7,
	 .desc = "Uops that flowed through the Store Unit",
	},
	{.name = "L1D_CACHE_WRITEBACK",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5a8,
	 .desc = "Dirty cache lines written back from the L1D Cache toward the Shared L2 Cache",
	},
	{.name = "LDST_X64_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5b1,
	 .desc = "Load and store uops that crossed a 64B boundary",
	},
	{.name = "LDST_XPG_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5b2,
	 .desc = "Load and store uops that crossed a 16KiB page boundary.  An SME access is considered cross-page if any bytes are accessed in the high portion (second page), regardless if any bytes are accessed in the low portion (first page), after predication is applied. An SME operation that only touches the low portion (first page) after predication is applied is not considered cross-page.",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_SUCC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5b3,
	 .desc = "Atomic or exclusive instruction successfully completed.  For exclusives, incorrectly undercounts for exclusives when the cache line is initially found in shared state, however counts correctly for atomics.",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_FAIL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5b4,
	 .desc = "Atomic or exclusive instruction failed due to contention.  For exclusives, incorrectly undercounts for exclusives when the cache line is initially found in shared state, however counts correctly for atomics.",
	},
	{.name = "ST_NT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5e5,
	 .desc = "Store uops that executed with non-temporal hint; includes SSVE/SME loads because they utilize the Store Unit",
	},
	{.name = "LD_NT_UOP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x5e6,
	 .desc = "Load uops that executed with non-temporal hint; excludes SSVE/SME loads because they utilize the Store Unit",
	},
	{.name = "FLUSH_RESTART_OTHER_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x884,
	 .desc = "Pipeline flush and restarts that were not due to branch mispredictions or memory order violations",
	},
	{.name = "INST_BRANCH_CALL",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x88e,
	 .desc = "Retired subroutine call instructions",
	},
	{.name = "INST_BRANCH_RET",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x88f,
	 .desc = "Retired subroutine return instructions",
	},
	{.name = "INST_BRANCH_TAKEN",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x890,
	 .desc = "Retired taken branch instructions",
	},
	{.name = "INST_BRANCH_INDIR",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x893,
	 .desc = "Retired indirect branch instructions including indirect calls",
	},
	{.name = "INST_BRANCH_COND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x894,
	 .desc = "Retired conditional branch instructions.  On M3 and prior, incorrectly only counts only B.cond instructions, where on M4 and following, adds CBZ/CBNZ/TBZ/TBNZ instructions to form the complete set of conditional branch instructions.",
	},
	{.name = "INST_INT_LD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x895,
	 .desc = "Retired load Integer Unit instructions",
	},
	{.name = "INST_INT_ST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x896,
	 .desc = "Retired store Integer Unit instructions.  Does not count DC ZVA (Data Cache Zero by VA).",
	},
	{.name = "INST_INT_ALU",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x897,
	 .desc = "Retired non-branch and non-load/store Integer Unit instructions",
	},
	{.name = "INST_SIMD_LD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x898,
	 .desc = "Retired load Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x899,
	 .desc = "Retired store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ALU",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x89a,
	 .desc = "Retired non-load/store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_LDST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x89b,
	 .desc = "Retired load and store instructions.  Does not count DC ZVA (Data Cache Zero by VA).",
	},
	{.name = "INST_BARRIER",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x89c,
	 .desc = "Retired data barrier instructions",
	},
	{.name = "INST_SIMD_ALU_VEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x89f,
	 .desc = "Retired non-load/store vector Advanced SIMD instructions",
	},
	{.name = "INST_SME_ENGINE_SCALARFP",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8a0,
	 .desc = "Retired scalar floating-point SME engine instructions",
	},
	{.name = "INST_SME_ENGINE_LD",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8a1,
	 .desc = "Retired load SME engine instructions",
	},
	{.name = "INST_SME_ENGINE_ST",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8a2,
	 .desc = "Retired store SME engine instructions",
	},
	{.name = "INST_SME_ENGINE_ALU",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8a3,
	 .desc = "Retired non-load/store SME engine instructions",
	},
	{.name = "L1D_CACHE_MISS_LD_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8bf,
	 .desc = "Retired loads that missed in the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_ST_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c0,
	 .desc = "Retired stores that missed in the L1 Data Cache",
	},
	{.name = "L1D_TLB_MISS_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c1,
	 .desc = "Retired loads and stores that missed in the L1 Data TLB",
	},
	{.name = "ST_MEM_ORDER_VIOL_LD_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c4,
	 .desc = "Retired core store uops that triggered memory order violations with core load uops",
	},
	{.name = "BRANCH_COND_MISPRED_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c5,
	 .desc = "Retired conditional branch instructions that mispredicted",
	},
	{.name = "BRANCH_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c6,
	 .desc = "Retired indirect branch instructions including calls and returns that mispredicted",
	},
	{.name = "BRANCH_RET_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8c8,
	 .desc = "Retired return instructions that mispredicted",
	},
	{.name = "BRANCH_CALL_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x8ca,
	 .desc = "Retired indirect call instructions mispredicted",
	},
	{.name = "L1I_CACHE_MISS_DEMAND",
	 .modmsk = ARMV9_ATTRS,
	 .code = 0x4006,
	 .desc = "Demand fetch misses that require a new cache line fill of the L1 Instruction Cache",
	},
	/* END M4 specific events */
};
