/*
 * Copyright The Asahi Linux Contributors
 * Contributed by Myria Sarvay <myrialsarvay@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Apple M1 Events
 * Hardware events extracted from /usr/share/kpep on macos
 */
static const arm_entry_t arm_apple_m1_pe[]={
	{.name = "RETIRE_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x01,
	 .desc = "All retired uops",
	},
	{.name = "CORE_ACTIVE_CYCLE",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x02,
	 .desc = "Cycles while the core was active",
	},
	{.name = "L1I_TLB_FILL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x04,
	 .desc = "Translations filled into the L1 Instruction TLB",
	},
	{.name = "L1D_TLB_FILL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x05,
	 .desc = "Translations filled into the L1 Data TLB",
	},
	{.name = "MMU_TABLE_WALK_INSTRUCTION",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x07,
	 .desc = "Table walk memory requests on behalf of instruction fetches",
	},
	{.name = "MMU_TABLE_WALK_DATA",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x08,
	 .desc = "Table walk memory requests on behalf of data accesses",
	},
	{.name = "L2_TLB_MISS_INSTRUCTION",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x0a,
	 .desc = "Instruction fetches that missed in the L2 TLB",
	},
	{.name = "L2_TLB_MISS_DATA",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x0b,
	 .desc = "Loads and stores that missed in the L2 TLB",
	},
	{.name = "MMU_VIRTUAL_MEMORY_FAULT_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x0d,
	 .desc = "Memory accesses that reached retirement that triggered any of the MMU virtual memory faults",
	},
	{.name = "SCHEDULE_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x52,
	 .desc = "Uops issued by the scheduler to any execution unit",
	},
	{.name = "INTERRUPT_PENDING",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x6c,
	 .desc = "Cycles while an interrupt was pending because it was masked",
	},
	{.name = "MAP_STALL_DISPATCH",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x70,
	 .desc = "Cycles while the Map Unit was stalled because of Dispatch back pressure",
	},
	{.name = "MAP_REWIND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x75,
	 .desc = "Cycles while the Map Unit was blocked while rewinding due to flush and restart",
	},
	{.name = "MAP_STALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x76,
	 .desc = "Cycles while the Map Unit was stalled for any reason",
	},
	{.name = "MAP_INT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x7c,
	 .desc = "Mapped Integer Unit uops",
	},
	{.name = "MAP_LDST_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x7d,
	 .desc = "Mapped Load and Store Unit uops, including GPR to vector register converts",
	},
	{.name = "MAP_SIMD_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x7e,
	 .desc = "Mapped Advanced SIMD and FP Unit uops",
	},
	{.name = "FLUSH_RESTART_OTHER_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x84,
	 .desc = "Pipeline flush and restarts that were not due to branch mispredictions or memory order violations",
	},
	{.name = "INST_ALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8c,
	 .desc = "All retired instructions",
	},
	{.name = "INST_BRANCH",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8d,
	 .desc = "Retired branch instructions including calls and returns",
	},
	{.name = "INST_BRANCH_CALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8e,
	 .desc = "Retired subroutine call instructions",
	},
	{.name = "INST_BRANCH_RET",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8f,
	 .desc = "Retired subroutine return instructions",
	},
	{.name = "INST_BRANCH_TAKEN",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x90,
	 .desc = "Retired taken branch instructions",
	},
	{.name = "INST_BRANCH_INDIR",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x93,
	 .desc = "Retired indirect branch instructions including indirect calls",
	},
	{.name = "INST_BRANCH_COND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x94,
	 .desc = "Retired conditional branch instructions (counts only B.cond)",
	},
	{.name = "INST_INT_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x95,
	 .desc = "Retired load Integer Unit instructions",
	},
	{.name = "INST_INT_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x96,
	 .desc = "Retired store Integer Unit instructions",
	},
	{.name = "INST_INT_ALU",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x97,
	 .desc = "Retired non-branch and non-load/store Integer Unit instructions",
	},
	{.name = "INST_SIMD_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x98,
	 .desc = "Retired load Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x99,
	 .desc = "Retired store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ALU",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9a,
	 .desc = "Retired non-load/store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_LDST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9b,
	 .desc = "Retired load and store instructions",
	},
	{.name = "INST_BARRIER",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9c,
	 .desc = "Retired data barrier instructions",
	},
	{.name = "L1D_TLB_ACCESS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa0,
	 .desc = "Load and store accesses to the L1 Data TLB",
	},
	{.name = "L1D_TLB_MISS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa1,
	 .desc = "Load and store accesses that missed the L1 Data TLB",
	},
	{.name = "L1D_CACHE_MISS_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa2,
	 .desc = "Stores that missed the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa3,
	 .desc = "Loads that missed the L1 Data Cache",
	},
	{.name = "LD_UNIT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa6,
	 .desc = "Uops that flowed through the Load Unit",
	},
	{.name = "ST_UNIT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa7,
	 .desc = "Uops that flowed through the Store Unit",
	},
	{.name = "L1D_CACHE_WRITEBACK",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xa8,
	 .desc = "Dirty cache lines written back from the L1D Cache toward the Shared L2 Cache",
	},
	{.name = "LDST_X64_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xb1,
	 .desc = "Load and store uops that crossed a 64B boundary",
	},
	{.name = "LDST_XPG_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xb2,
	 .desc = "Load and store uops that crossed a 16KiB page boundary",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_SUCC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xb3,
	 .desc = "Atomic or exclusive instruction successfully completed",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_FAIL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xb4,
	 .desc = "Atomic or exclusive instruction failed (due to contention)",
	},
	{.name = "L1D_CACHE_MISS_LD_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xbf,
	 .desc = "Retired loads that missed in the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_ST_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc0,
	 .desc = "Retired stores that missed in the L1 Data Cache",
	},
	{.name = "L1D_TLB_MISS_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc1,
	 .desc = "Retired loads and stores that missed in the L1 Data TLB",
	},
	{.name = "ST_MEMORY_ORDER_VIOLATION_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc4,
	 .desc = "Retired stores that triggered memory order violations",
	},
	{.name = "BRANCH_COND_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc5,
	 .desc = "Retired conditional branch instructions that mispredicted",
	},
	{.name = "BRANCH_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc6,
	 .desc = "Retired indirect branch instructions including calls and returns that mispredicted",
	},
	{.name = "BRANCH_RET_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc8,
	 .desc = "Retired return instructions that mispredicted",
	},
	{.name = "BRANCH_CALL_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xca,
	 .desc = "Retired indirect call instructions mispredicted",
	},
	{.name = "BRANCH_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xcb,
	 .desc = "Retired branch instructions including calls and returns that mispredicted",
	},
	{.name = "L1I_TLB_MISS_DEMAND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xd4,
	 .desc = "Demand instruction fetches that missed in the L1 Instruction TLB",
	},
	{.name = "MAP_DISPATCH_BUBBLE",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xd6,
	 .desc = "Bubble detected in dispatch stage",
	},
	{.name = "L1I_CACHE_MISS_DEMAND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xdb,
	 .desc = "Demand fetch misses that require a new cache line fill of the L1 Instruction Cache",
	},
	{.name = "FETCH_RESTART",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xde,
	 .desc = "Fetch Unit internal restarts for any reason. Does not include branch mispredicts",
	},
	{.name = "ST_NT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xe5,
	 .desc = "Store uops that executed with non-temporal hint",
	},
	{.name = "LD_NT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xe6,
	 .desc = "Load uops that executed with non-temporal hint",
	},
	/* END M1 specific events */
};
