/*
 * Copyright The Asahi Linux Contributors
 * Contributed by Myria Sarvay <myrialsarvay@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Apple M3 Events
 * Hardware events extracted from /usr/share/kpep on macos
 */
static const arm_entry_t arm_apple_m3_pe[]={
	{.name = "RETIRE_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x1,
	 .desc = "All retired uops",
	},
	{.name = "CORE_ACTIVE_CYCLE",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x2,
	 .desc = "Cycles while the core was active",
	},
	{.name = "FLUSH_RESTART_OTHER_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x84,
	 .desc = "Pipeline flush and restarts that were not due to branch mispredictions or memory order violations",
	},
	{.name = "INST_ALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8c,
	 .desc = "All retired instructions",
	},
	{.name = "INST_BRANCH",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8d,
	 .desc = "Retired branch instructions including calls and returns",
	},
	{.name = "INST_BRANCH_CALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8e,
	 .desc = "Retired subroutine call instructions",
	},
	{.name = "INST_BRANCH_RET",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x8f,
	 .desc = "Retired subroutine return instructions",
	},
	{.name = "INST_BRANCH_TAKEN",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x90,
	 .desc = "Retired taken branch instructions",
	},
	{.name = "INST_BRANCH_INDIR",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x93,
	 .desc = "Retired indirect branch instructions including indirect calls",
	},
	{.name = "INST_INT_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x95,
	 .desc = "Retired load Integer Unit instructions",
	},
	{.name = "INST_INT_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x96,
	 .desc = "Retired store Integer Unit instructions.  Does not count DC ZVA (Data Cache Zero by VA).",
	},
	{.name = "INST_INT_ALU",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x97,
	 .desc = "Retired non-branch and non-load/store Integer Unit instructions",
	},
	{.name = "INST_SIMD_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x98,
	 .desc = "Retired load Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x99,
	 .desc = "Retired store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_SIMD_ALU",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9a,
	 .desc = "Retired non-load/store Advanced SIMD and FP Unit instructions",
	},
	{.name = "INST_LDST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9b,
	 .desc = "Retired load and store instructions.  Does not count DC ZVA (Data Cache Zero by VA).",
	},
	{.name = "INST_BARRIER",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9c,
	 .desc = "Retired data barrier instructions",
	},
	{.name = "INST_SIMD_ALU_VEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x9f,
	 .desc = "Retired non-load/store vector Advanced SIMD instructions",
	},
	{.name = "L1D_CACHE_MISS_LD_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xbf,
	 .desc = "Retired loads that missed in the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_ST_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc0,
	 .desc = "Retired stores that missed in the L1 Data Cache",
	},
	{.name = "L1D_TLB_MISS_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc1,
	 .desc = "Retired loads and stores that missed in the L1 Data TLB",
	},
	{.name = "ST_MEM_ORDER_VIOL_LD_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc4,
	 .desc = "Retired core store uops that triggered memory order violations with core load uops",
	},
	{.name = "BRANCH_COND_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc5,
	 .desc = "Retired conditional branch instructions that mispredicted",
	},
	{.name = "BRANCH_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc6,
	 .desc = "Retired indirect branch instructions including calls and returns that mispredicted",
	},
	{.name = "BRANCH_RET_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xc8,
	 .desc = "Retired return instructions that mispredicted",
	},
	{.name = "BRANCH_CALL_INDIR_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xca,
	 .desc = "Retired indirect call instructions mispredicted",
	},
	{.name = "BRANCH_MISPRED_NONSPEC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0xcb,
	 .desc = "Instruction architecturally executed, mispredicted branch",
	},
	{.name = "MAP_DISPATCH_BUBBLE_IC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x182,
	 .desc = "Cycles while the Map Unit had no uops to process due to L1 Instruction Cache and was not stalled",
	},
	{.name = "MAP_DISPATCH_BUBBLE_ITLB",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x183,
	 .desc = "Cycles while the Map Unit had no uops to process due to L1 Instruction TLB and was not stalled",
	},
	{.name = "DECODE_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x186,
	 .desc = "Decoded uops",
	},
	{.name = "L1I_TLB_MISS_DEMAND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x1d4,
	 .desc = "Demand instruction fetches that missed in the L1 Instruction TLB",
	},
	{.name = "MAP_DISPATCH_BUBBLE",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x1d6,
	 .desc = "Cycles while the Map Unit had no uops to process and was not stalled",
	},
	{.name = "L1I_CACHE_MISS_DEMAND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x1db,
	 .desc = "Demand fetch misses that require a new cache line fill of the L1 Instruction Cache",
	},
	{.name = "FETCH_RESTART",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x1de,
	 .desc = "Fetch Unit internal restarts for any reason. Does not include branch mispredicts",
	},
	{.name = "MAP_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x269,
	 .desc = "Mapped uops",
	},
	{.name = "INTERRUPT_PENDING",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x26c,
	 .desc = "Cycles while an interrupt was pending because it was masked",
	},
	{.name = "MAP_STALL_DISPATCH",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x270,
	 .desc = "Cycles while the Map Unit was stalled because of Dispatch back pressure",
	},
	{.name = "MAP_REWIND",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x275,
	 .desc = "Cycles while the Map Unit was blocked while rewinding due to flush and restart",
	},
	{.name = "MAP_STALL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x276,
	 .desc = "Cycles while the Map Unit was stalled for any reason",
	},
	{.name = "MAP_INT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x27c,
	 .desc = "Mapped Integer Unit uops",
	},
	{.name = "MAP_LDST_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x27d,
	 .desc = "Mapped Load and Store Unit uops, including GPR to vector register converts.  Includes all instructions sent to the SME engine because they are processed through the Store Unit.",
	},
	{.name = "MAP_SIMD_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x27e,
	 .desc = "Mapped Advanced SIMD and FP Unit uops",
	},
	{.name = "SCHEDULE_UOP_ANY",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x283,
	 .desc = "Cycles while the uop scheduler issued at least 1 uop to any execution unit",
	},
	{.name = "LDST_UNIT_OLD_L1D_CACHE_MISS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x290,
	 .desc = "Cycles while an old load or store uop is waiting for data after an L1 Data Cache miss",
	},
	{.name = "LDST_UNIT_WAITING_OLD_L1D_CACHE_MISS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x291,
	 .desc = "Cycles while an old load or store uop is waiting for data after an L1 Data Cache miss, and no uop was issued by the scheduler, prioritized",
	},
	{.name = "SCHEDULE_EMPTY",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x351,
	 .desc = "Cycles while the uop scheduler is empty",
	},
	{.name = "L1I_TLB_FILL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x404,
	 .desc = "Translations filled into the L1 Instruction TLB",
	},
	{.name = "L1D_TLB_FILL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x405,
	 .desc = "Translations filled into the L1 Data TLB",
	},
	{.name = "MMU_TABLE_WALK_INSTRUCTION",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x407,
	 .desc = "Table walk memory requests on behalf of instruction fetches",
	},
	{.name = "MMU_TABLE_WALK_DATA",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x408,
	 .desc = "Table walk memory requests on behalf of data accesses",
	},
	{.name = "L2_TLB_MISS_INSTRUCTION",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x40a,
	 .desc = "Instruction fetches that missed in the L2 TLB",
	},
	{.name = "L2_TLB_MISS_DATA",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x40b,
	 .desc = "Loads and stores that missed in the L2 TLB",
	},
	{.name = "L1D_TLB_ACCESS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a0,
	 .desc = "Load and store accesses to the L1 Data TLB",
	},
	{.name = "L1D_TLB_MISS",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a1,
	 .desc = "Load and store accesses that missed the L1 Data TLB",
	},
	{.name = "L1D_CACHE_MISS_ST",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a2,
	 .desc = "Stores that missed the L1 Data Cache",
	},
	{.name = "L1D_CACHE_MISS_LD",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a3,
	 .desc = "Loads that missed the L1 Data Cache",
	},
	{.name = "LD_UNIT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a6,
	 .desc = "Uops that flowed through the Load Unit",
	},
	{.name = "ST_UNIT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a7,
	 .desc = "Uops that flowed through the Store Unit",
	},
	{.name = "L1D_CACHE_WRITEBACK",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5a8,
	 .desc = "Dirty cache lines written back from the L1D Cache toward the Shared L2 Cache",
	},
	{.name = "LDST_X64_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5b1,
	 .desc = "Load and store uops that crossed a 64B boundary",
	},
	{.name = "LDST_XPG_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5b2,
	 .desc = "Load and store uops that crossed a 16KiB page boundary.  An SME access is considered cross-page if any bytes are accessed in the high portion (second page), regardless if any bytes are accessed in the low portion (first page), after predication is applied. An SME operation that only touches the low portion (first page) after predication is applied is not considered cross-page.",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_SUCC",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5b3,
	 .desc = "Atomic or exclusive instruction successfully completed.  For exclusives, incorrectly undercounts for exclusives when the cache line is initially found in shared state, however counts correctly for atomics.",
	},
	{.name = "ATOMIC_OR_EXCLUSIVE_FAIL",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5b4,
	 .desc = "Atomic or exclusive instruction failed due to contention.  For exclusives, incorrectly undercounts for exclusives when the cache line is initially found in shared state, however counts correctly for atomics.",
	},
	{.name = "ST_NT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5e5,
	 .desc = "Store uops that executed with non-temporal hint; includes SSVE/SME loads because they utilize the Store Unit",
	},
	{.name = "LD_NT_UOP",
	 .modmsk = ARMV8_ATTRS,
	 .code = 0x5e6,
	 .desc = "Load uops that executed with non-temporal hint; excludes SSVE/SME loads because they utilize the Store Unit",
	},
	/* END M1 specific events */
};
